# -*- coding: utf-8 -*-
"""2702221936-Jeffrey Ferdinand Hartono-Numpy.LiNALG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T37zoUM0p69h7aQiPvvIW6jQX3M8tueu
"""

import numpy as np
A = np.array([[4, 3, -5],
              [-2, -4, 5],
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A,y)
print(x)

A_inv = np.linalg.inv(A)

x = np.dot(A_inv, y)
print(x)